const SessionConstants = {
  SESSION_RECEIVED: "SESSION_RECEIVED",
  SESSION_DESTROYED: "SESSION_DESTROYED",
  INVALID_ENTRY: "INVALID_ENTRY",
  APPLICATION_RECEIVED: "APPLICATION_RECEIVED"
}

module.exports = SessionConstants;
